---

- name: Check that license keys are defined
  fail:
    msg: "'license' has to be defined for each php setup, for help visit: https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#ingest-license-key"
  when: item.license | default(False) == False
  loop: "{{ anrpa_php_installations }}"

- name: Check that application names are defined
  fail:
    msg: "'appname' has to be defined for each php setup, for help visit: https://docs.newrelic.com/docs/agents/php-agent/configuration/name-your-php-application/"
  when: item.appname | default(False) == False
  loop: "{{ anrpa_php_installations }}"

- name: Check that php installation bin paths are defined
  fail:
    msg: "'php_path' has to be defined for each php setup, for help visit: https://github.com/visdmin/ansible-new-relic-php-agent/blob/main/README.md"
  when: item.bin_path | default(False) == False
  loop: "{{ anrpa_php_installations }}"

- name: Check that php installation config paths are defined
  fail:
    msg: "'config_path' has to be defined for each php setup, for help visit: https://github.com/visdmin/ansible-new-relic-php-agent/blob/main/README.md"
  when: item.config_path | default(False) == False
  loop: "{{ anrpa_php_installations }}"

- name: Install new relic yum 64 bit repository
  shell: rpm -Uvh {{ anrpa_new_relic_64bit_repo_url }}
  when: ansible_architecture == "64 bits"

- name: Install new relic yum 32 bit repository
  shell: rpm -Uvh {{ anrpa_new_relic_32bit_repo_url }}
  when: ansible_architecture == "32 bits"

- name: Install new relic php agent package
  yum:
    name: "{{ anrpa_php_agent_package_name }}"
    state: "{{ anrpa_installation_state|default('latest') }}"
    update_cache: true
  register: php_agent_installed

- name: Run new relic php agent install
  shell: "newrelic-install install"
  environment:
    NR_INSTALL_SILENT: true
    NR_INSTALL_KEY: "{{ item.license }}"
    NR_INSTALL_PATH: "{{ item.bin_path }};"
  loop: "{{ anrpa_php_installations }}"
  when: php_agent_installed.changed

- name: Setup new relic php.ini files
  vars:
    config: "{{ item }}"
  template:
    src: newrelic.php.ini.j2
    dest: "{{ item.config_path }}/{{ anrpa_php_ini_filename }}"
    group: root
    owner: root
    mode: 0640
  when: item.state|default('present') == 'present'
  loop: "{{ anrpa_php_installations }}"
  notify:
    - restart new relic php agent
    - restart php-fpm
    - restart web-server

- name: Remove new relic php.ini files for disabled installations
  file:
    dest: "{{ item.config_path }}/{{ anrpa_php_ini_filename }}"
    state: absent
  when: item.state|default('present') != 'present'
  loop: "{{ anrpa_php_installations }}"
  notify:
    - restart new relic php agent
    - restart php-fpm
    - restart web-server
