---

- name: Install new relic php agent
  import_tasks: install.yml
  when: anrpa_state|default('latest') != 'absent'

- name: Uninstall new relic php agent
  import_tasks: uninstall.yml
  when: anrpa_state|default('latest') == 'absent'
