---
# handlers file for ansible-new-relic-php-agent

- name: restart php-fpm
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ item.php_fpm_service_name }}"
  when: (item.php_fpm_service_name is defined) and (item.php_fpm_service_name|length != 0)
  loop: "{{ anrpa_php_installations }}"

- name: restart web-server
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ item.web_server_service_name }}"
  when: (item.web_server_service_name is defined) and (item.web_server_service_name|length != 0)
  loop: "{{ anrpa_php_installations }}"

- name: restart new relic php agent
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ anrpa_php_agent_service_name }}"

- name: stop new relic php agent
  systemd:
    state: stopped
    enabled: false
    name: "{{ anrpa_php_agent_service_name }}"
